site:
  baseUrl: "https://copper-leaf.github.io/kodiak"
  theme: "Copper"
  about:
    siteName: Kodiak
    siteDescription: Wrappers around code documentation CLI tools to produce JSON models, usable as libraries

theme:
  social:
    other:
      - link: 'https://copper-leaf.github.io/kodiak'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/copper-leaf/kodiak'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  logo: 'assets/media/theme-logo.png'
  sidebarBackground: 'primary'
  sidebarBackgroundType: GRADIENT
  colors:
    blue: '#48BAEF'
  palette:
    primary: 'BLUE'
    link: 'BLUE'

services:
  publications:
    stages:
      - type: 'githubPages'
        repo: 'copper-leaf/kodiak'
        username: 'cjbrooks12'
      - type: 'githubReleases'
        repo: 'copper-leaf/kodiak'

allPages:
  components:
    - type: "pageContent"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - java
        - kotlin
        - groovy
        - swift
  menu:
    - type: 'page'
      title: 'Home'
      itemId: 'Home'
    - type: 'page'
      itemId: 'Changelog'

    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
      asSubmenu: true

    - type: 'separator'
      title: 'Supported Languages'
    - type: "sourcedocModules"
      moduleType: 'kotlindoc'
      moduleGroup: 'languages'
      asSubmenu: true
  layoutConfig:
    pageContentsMenu:
      - type: 'separator'
        title: 'In This Page'
      - type: 'pageIds'
        structure: nested
        maxLevel: 2
